### ISSUE TITLE
Trademark

### ISSUE THREAD

**Issue by GXL7** [thebigsmileXD/PocketAI#8]
To whom this may concern,

We have been trying to contact the author of this software, to inform you that you are infringing on a trademark. Please be advised that PocketAI is a trademark of 3D Net Productions. 

Thank you,
GL

**Comment by inxomnyaa** [comment]
There were no tries of contacting me at all.

Nothing would stop me naming my repository "Microsoft".

Also, i search repository names on Google before i create a repository. This company nor the name showed up when this repo was created.

**Comment by inxomnyaa** [comment]
I'd like to see the trademark entry before anything.

Also: this program uses the Windows 98 icon. Afaik it is licensed, you are allowed to use it?
